[package]
name = "bft-crdts"
version = "0.1.0"
authors = ["David Rusu <davidrusu.me@gmail.com>"]
edition = "2018"

[dependencies]
crdts = "4.0.0"
ed25519-dalek = { version = "0.9.1", features = ["serde"] }
rand = "0.6"
sha2 = "0.8.1"
serde = "1.0.106"
bincode = "1.2.1"
hex = "0.4.2"

[profile.test]
# Property testing is a power hungry beast, we need to go as fast as we can
opt-level = 3
lto = "fat" # noticed a very significant speed up from enabling lto, perf improvement of 1m33s -> 10s
incremental = false
